version: "3.8"
services:
  php74_blade:
    container_name: php74_blade
    build:
      context: .
      dockerfile: ./.docker/PHP74_Dockerfile
    volumes:
      - .:/var/www/html
    init: true
    # restart: unless-stopped
    command: vendor/bin/phpunit tests/Unit/

  php80_blade:
    container_name: php80_blade
    build:
      context: .
      dockerfile: ./.docker/PHP80_Dockerfile
    volumes:
      - .:/var/www/html
    init: true
    # restart: unless-stopped
    command: vendor/bin/phpunit tests/Unit/
    depends_on:
      - php74_blade

  php81_blade:
    container_name: php81_blade
    build:
      context: .
      dockerfile: ./.docker/PHP81_Dockerfile
    volumes:
      - .:/var/www/html
    init: true
    # restart: unless-stopped
    command: vendor/bin/phpunit tests/Unit/
    depends_on:
      - php80_blade

  php82_blade:
    container_name: php82_blade
    build:
      context: .
      dockerfile: ./.docker/PHP82_Dockerfile
    volumes:
      - .:/var/www/html
    init: true
    # restart: unless-stopped
    command: vendor/bin/phpunit tests/Unit/
    depends_on:
      - php81_blade
