version: "3.8"
services:
  php74_calendarar:
    container_name: php74_calendarar
    build:
      context: .
      dockerfile: ./.docker/PHP74_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    command: vendor/bin/phpunit tests/Unit/

  php80_calendarar:
    container_name: php80_calendarar
    build:
      context: .
      dockerfile: ./.docker/PHP80_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    command: vendor/bin/phpunit tests/Unit/
    depends_on:
      - php74_calendarar

  php81_calendarar:
    container_name: php81_calendarar
    build:
      context: .
      dockerfile: ./.docker/PHP81_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    command: vendor/bin/phpunit tests/Unit/
    depends_on:
      - php80_calendarar

  php82_calendarar:
    container_name: php82_calendarar
    build:
      context: .
      dockerfile: ./.docker/PHP82_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    command: vendor/bin/phpunit tests/Unit/
    depends_on:
      - php81_calendarar
